server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Demo
    username: postgres
    password: postgray
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      
  data:
    redis:
      host: localhost
      port: 6379